name: Add reviewers to release PRs

on:
  # pull_request_target:
  #   branches: ['master', 'next']
  #   types: ['labeled']
  workflow_dispatch:

permissions: {}

jobs:
  add-reviewers-to-release-pr:
    uses: mui/mui-public/.github/workflows/reusable-add-f87c4b1b022bb383419be7979bcb05c4e343499bs-to-pr.yml@f87c4b1b022bb383419be7979bcb05c4e343499b-action
    with:
      team-slug: x
      label-name: release
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
